# Generated by Django 5.2a1 on 2025-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Career', 'Career'), ('Finance', 'Finance'), ('Personal', 'Personal'), ('Education', 'Education'), ('Wellness', 'Wellness')], max_length=200),
        ),
    ]
