# Generated by Django 5.2a1 on 2025-04-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0004_milestone'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='User.user'),
            preserve_default=False,
        ),
    ]
