# Generated by Django 5.2a1 on 2025-04-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0005_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
